/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swp_steuerung_HeadTracker */

#ifndef _Included_swp_steuerung_HeadTracker
#define _Included_swp_steuerung_HeadTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swp_steuerung_HeadTracker
 * Method:    detectFace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_swp_steuerung_HeadTracker_detectFace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
